machine:
    node:
        version: 6.3.1
    hosts:
        localhost: 127.0.0.1
jobs:
   build:
     docker:
       - image: circleci/node:6.10.3
       - image: circleci/mongo:3.4.4
     steps:
       - checkout
       - run: npm install
       - run:
           name: Instantiate github-keys.json
           command: 'echo "{ \"clientID\": \"$GITHUB_CLIENT_ID\", \"clientSecret\": \"$GITHUB_CLIENT_SECRET\", \"callbackURL\": \"$GITHUB_CALLBACK_URL\"}">github-keys.json'
       - run:
           name: Run server in background
           command: 'npm start'
           background: true
       - run: sleep 5
